server:
  port: 8081
security:
  oauth2:
    client:
      client-id: crizcroz-api
      client-secret: crizcroz-api-secret
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
